repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        entry: uv run ruff check src/
        language: system
        pass_filenot: true
        types: [python]
      - id: mypy-check
        name: mypy check
        entry: uv run mypy src/
        language: system
        pass_filenot: true
        types: [python]